### ISSUE TITLE
request: to be supported by ComfyUI-Manager, a change in the node structure is necessary.

### ISSUE THREAD

**Issue by ltdrdata** [osi1880vr/prompt_quill_comfyui#1]
1. If dependencies need to be installed via `requirements.txt`, they must not be installed using the `copy` method.
2. Additionally, to support updates, the copy method should be avoided and the git-clone method should be used.
3. Your node's `__init__.py` includes logic to install `requirements.txt`.  If you do this, the installation will be executed every time your node is imported in ComfyUI. Please separate the installation logic into `install.py`.
4. During the installation phase, if there are only package dependencies in `requirements.txt`, ComfyUI-Manager will handle the installation, so there is no need for separate install logic.

For now, your node has been temporarily moved to the dev channel.

**Comment by osi1880vr** [comment]
Hey, thanks for the plenty advice, I'm a total noob in creating nodes and so I'm happy for your helping hand.
I removed any pointer to requirements.txt from the __init__.py, also I did not add any install.py as it for now it can live with pure Python except for clip which is already there anyways. I did check in my fork from the manager to make another pull request but somehow I found prompt quill twice in the list in my fork, that confused me so I don't change a thing for now on that front. Maybe you can advise any further step. I'm here to follow blindly =)

**Comment by osi1880vr** [comment]
Oh, I should read more before I answer =) I checked on the dev channel and did a fresh install from there. it has worked so far with no issues.

**Comment by osi1880vr** [comment]
OK Done =)

**Comment by ltdrdata** [comment]
Thanks. I moved your node to default channel.
